# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 894a560cffbb4d271d61da994ae0fb02ee2f88d3e280984157146e0798474925553e0cbd6209b08013115b79500e48aaaae0af6420766a02f5ce7e0702272e3b
  private_mailgun_api: key-8429860484dd1289ee968b3a714de673
  mailgun_domain: mg.avtrujillo.com
  my_email: alexandervtrujillo@gmail.com
test:
  secret_key_base: a32ed9cc752c6c00b9e6bb77d72e8e832027879466da429f6a408d45ab5894de5e6f475a39ee62a5522d1cd28eabfea11332115b206c017d076767c55f68795d
  private_mailgun_api: key-8429860484dd1289ee968b3a714de673
  mailgun_domain: mg.avtrujillo.com

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
